### PR TITLE
Format Haskell code with Ormolu

### PR DESCRIPTION
**Pull request by afcowie**
Wow, it sure is confronting to see your source code in a different code style. I'm mostly ok with it, though the fact they choke on multi-line comments being used as Haddock is frustrating. Alas.

### CODE REVIEW

**Comment by afcowie** [comment]
I miss my whitespace.

**Comment by afcowie** [comment]
Didn't realize GitHub has a "Draft" feature now for Pull Requests. Cool. That's much better use when building up work-in-progress branches than having a `work-in-progress` tag.

**Comment by carlosdagos** [comment]
Is ormolu doing 2 space indentation? 😱 

That will be hard to get over

**Comment by afcowie** [comment]
> Is ormolu doing 2 space indentation? scream

Yeah, I know. I've been a 4 spaces guy for a long time. I believe it comes from its heritage in the style Johan Tibell wrote for **hindent**, which Chris Done later adopted as the only style available.

That said I've noticed that when there's nested brackets or parentheses you end up with considerable indentation. I'm learning to live with it.

That said if they ever give us an option to have 4 spaces back I'll take it `:)`

**Pull request merged**
